{{- if not .Values.profiles2.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brouter.fullname" . }}-profiles2
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    {{- include "brouter.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "profiles2/*").AsConfig | nindent 2 }}
{{- end }}
