apiVersion: v2
name: brouter
description: A Helm chart for BRouter (https://github.com/abrensch/brouter)

type: application

version: 0.7.0

# when you bump the appVersion to a newer BRouter release, also update the version for the .brf and .dat downloads in values.yaml
appVersion: "v1.7.9"
